project_id = "blamqqituncagdxwpwkp"

[functions.transcribe-audio]
verify_jwt = false

[functions.analyze-journal]
verify_jwt = false

[functions.generate-logo]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false
