name: ğŸš€ Build and Deploy Website
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: ğŸ‰ Build & Sync
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ğŸ—ï¸ Install and Build
      run: |
        npm install
        npm run build
        # Verify the build output
        ls -R dist

    - name: ğŸ“‚ Sync files to Swizzonic
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        local-dir: ./dist/public/
